[package]
name = "simple_rust_web_scraper"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.1"
reqwest = { version = "0.12.12", features = ["blocking"] }
scraper = "0.22.0"
tidier = "0.5.3"
